on:
  pull_request:

jobs:
  test-a:
    runs-on: ubuntu-latest
    steps:
      - name: setup node sha
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      - name: setup node version
        uses: actions/setup-node@v4.4.0
      - name: setup node main
        uses: actions/setup-node@main

  test-b:
    runs-on: ubuntu-latest
    steps:
      - name: cache sha
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      - name: cache sha with subpath
        uses: actions/cache/save@d4323d4df104b026a6aa633fdb11d772146be0bf

      - name: cache version
        uses: actions/cache@v4.2.2
      - name: cache version with subpath
        uses: actions/cache/save@v4.2.2

      - name: cache major version
        uses: actions/cache@v3
      - name: cache major version with subpath
        uses: actions/cache/save@v3
