on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup node with sha
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      - name: another step
        run: echo "This is another step"